# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# original script by maximilian.huber@tngtech.com
# additions by michael.c.jaeger@siemens.com
#
# SPDX-License-Identifier: GPL-2.0
#
# this script starts a VM in order to run project builder inside
# for development and debugging
#

#
# std vagrant setup
#
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "3072"]
    vbox.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.synced_folder "..", "/home/vagrant/prj/fossology", type: "rsync"
  config.vm.network "forwarded_port", guest: 80, host: 8082

#
# part to prepare dependencies
#
  config.vm.provision "shell" do |s|
    s.inline = <<SCRIPT
set -ex

yum install -y wget git

# install EPEL
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh epel-release-latest-7.noarch.rpm

# install projectbuilder
wget http://ftp.project-builder.org/test/centos/7/x86_64/pb-test.repo
cp pb-test.repo /etc/yum.repos.d/

# not using gpg checking is not recommended
# yum update -y --nogpgcheck
# yum install -y project-builder --nogpgcheck
yum update -y
yum install -y project-builder

# adding docker install info for prepping the project builder installation runs
cat > /etc/yum.repos.d/docker.repo << EOF
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

# ... then installing docker
yum install -y docker-engine

# ... starting docker
systemctl start docker

# ... installing composer things
# cd /home/vagrant/prj/fossology
mkdir -p /home/vagrant/composer/
/home/vagrant/prj/fossology/utils/install_composer.sh /home/vagrant/composer/
export COMPOSER_PHAR=/home/vagrant/composer/composer
mkdir /home/vagrant/prj/fossology/src/vendor
chown vagrant:vagrant /home/vagrant/prj/fossology/src/vendor

# ... should be done, but possible only later
# cd /home/vagrant/prj/fossology/src/
# make DESTDIR=/home/vagrant/prj/fossology/src/ MODDIR=vendor/ composer_install

SCRIPT
  end

#
# checking out and preparing project builder
# note that triple backslashes are because of cat and vagrant escaping
#
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline = <<SCRIPT
sudo chown vagrant:vagrant ~/prj
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

set -ex

################################################################################
# configure pb
cat<<PBRC > $HOME/.pbrc

pbdefdir default = \\\$ENV{HOME}/cache-project-builder
pbstoponerr default = true

pburl fossology = git+https://github.com/fossology/fossology.git
pbdefdir fossology =  \\\$ENV{'HOME'}/prj
pbconfurl fossology = git+https://github.com/fossology/fossology.git
pbconfdir fossology = \\\$ENV{'HOME'}/prj/fossology/pbconf

PBRC

################################################################################
#sbx = sandbox

# git checkout could be done here if need for overwrite is needed ...

pb -t -p fossology sbx2build   fossology
pb    -p fossology build2prep  fossology
# actually, sbx2pkg is included in sbx2pkg2ins
#pb -t -p fossology sbx2pkg     fossology 
pb -t -p fossology sbx2pkg2ins fossology

SCRIPT
  end

#
# applying some work around
#
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline = <<SCRIPT
# todo disabling SELinux only at first start is needed but should be put in policies
# remove if the https://github.com/fossology/fossology/issues/727
sudo setenforce 0

SCRIPT
  end

end
